# Deploy a static website using a Kubernetes Deployment and expose it using a NodePort Service.
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector: # Service gets attached to the workload having the same labels
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector: # defines how the created ReplicaSet finds which Pods to manage
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
########################################################################
# For results see visit -->> NodeIp:NodePort
# For minikube get service url to see reults
