apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
  labels:
    name: stg
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      name: stg
