apiVersion: v1
kind: Namespace
metadata:
  name: development1
  labels:
    name: configMap-testing
---
apiVersion: v1
kind: Namespace
metadata:
  name: development2
  labels:
    name: configMap-testing
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  namespace: development1
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmapsync-operator
  namespace: development1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmapsync-operator
  template:
    metadata:
      labels:
        app: configmapsync-operator
    spec:
      containers:
        - name: configmapsync-operator
          image: zdrok/configmapsync-operator:latest
