apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .secret-file: dmFsdWUtMg0KDQo= # Will create a hidden file in volume mount
  normal-file: dmFsdWUtMg0KDQo= # Will create a normal file in volume mount
