apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-blue
  labels:
    app: tomcat
    role: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
      role: blue
  template:
    metadata:
      labels:
        app: tomcat
        role: blue
    spec:
      containers:
        - name: tomcat-container
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-green
  labels:
    app: tomcat
    role: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
      role: green
  template:
    metadata:
      labels:
        app: tomcat
        role: green
    spec:
      containers:
        - name: tomcat-container
          image: nginx
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
