kind: Service
apiVersion: v1
metadata:
  name: tomcat-service
  labels:
    app: tomcat
    role: green
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: tomcat
    role: green
  ports:
    - port: 80
      targetPort: 80
