kind: Service
apiVersion: v1
metadata:
  name: tomcat-test-green
  labels:
    app: tomcat
    role: test-green
spec:
  type: LoadBalancer
  selector:
    app: tomcat
    role: green
  ports:
    - port: 80
      targetPort: 8080
