name: Deploy to AKS

on:
  push:
    branches: ["github-action"]

env:
  IMAGE_NAME: paladian78/chat-room:latest
  AKS_RESOURCE_GROUP: RG-Playground-Y001
  AKS_CLUSTER_NAME: myaks

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: ./Pipeline/app

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to AKS
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
      - run: |
          kubectl apply -f app.yaml
